apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpc-review
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpc-review
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: mpc-review
    spec:
      containers:
      - name: mpc-review
        image: fadedreams7/mpc-review:latest #local image
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: review
          containerPort: 3007
        env:
          - name: ENABLE_APM
            value: '1'
          - name: NODE_ENV
            value: 'production'
          - name: GATEWAY_JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: gateway-jwt-token
          - name: JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: jwt-token
          - name: RABBITMQ_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-rabbitmq-endpoint
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-postgres-host
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-postgres-user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-postgres-password
          - name: DATABASE_NAME
            value: 'mpc_reviews'
          - name: API_GATEWAY_URL
            value: 'http://mpc-gateway.production.svc.cluster.local:3000'
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-elasticsearch-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key:  mpc-elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-elastic-apm-secret-token

---

apiVersion: v1
kind: Service
metadata:
  name: mpc-review
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: mpc-review
  ports:
  - name: review
    port: 3007
    targetPort: 3007
    protocol: TCP
