
FROM node:21-alpine3.18 as builder

WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
COPY src ./src

RUN npm install -g pnpm && pnpm install --only=prod
RUN pnpm ci && pnpm run build

FROM node:21-alpine3.18

WORKDIR /app
RUN apk add --no-cache curl
COPY package*.json ./
COPY tsconfig.json ./
RUN pnpm install -g pm2 npm@latest
RUN pnpm ci --production
COPY --from=builder /app/build ./build

EXPOSE 3001

CMD [ "pnpm", "run", "build" ]
