apiVersion: v1
kind: ConfigMap
metadata:
  name: keydb-config
  namespace: production
data:
  keydb.conf: |
    bind 0.0.0.0
    port 6379
    databases 16
    save 900 1
    save 300 10
    save 60 10000
