apiVersion: v1
kind: PersistentVolume
metadata:
  name: keydb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: keydb-storage
  hostPath:
    path: /data/keydb
