
apiVersion: v1
kind: Secret
metadata:
  name: mpc-secret
  namespace: production
type: Opaque
data:
  # echo -n <secret> | base64
  secret-key-one: c2VjcmV0=
  secret-key-two: c2VjcmV0=
  gateway-jwt-token: c2VjcmV0
  jwt-token: c2VjcmV0
  # echo -n redis://:mpc@mpc-redis.production.svc.cluster.local:6379 | base64
  mpc-redis-host: cmVkaXM6Ly86bXBjQG1wYy1yZWRpcy5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzk=
  sender-email: c2VjcmV0
  sender-email-password: c2VjcmV0
  # echo -n mysql://mpc:mpc@mpc-mysql.production.svc.cluster.local:3306 | base64
  mpc-mysql-db: bXlzcWw6Ly9tcGM6bXBjQG1wYy1teXNxbC5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjMzMDY=
  mpc-postgres-host: c2VjcmV0
  mpc-postgres-user: c2VjcmV0
  mpc-postgres-password: c2VjcmV0
  # echo -n mongodb://mpc-mongo.production.svc.cluster.local:27017 | base64
  mongo-database-url: bW9uZ29kYjovL21wYy1tb25nby5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3
  mpc-rabbitmq-user: c2VjcmV0
  mpc-rabbitmq-password: am9iYmVycGFzcwc2VjcmV0
  # echo -n amqp://mpc:mpc@mpc-queue.production.svc.cluster.local:5672 | base64
  mpc-rabbitmq-endpoint: c2VjcmV0
  # echo -n http://elastic:changeme@mpc-elastic.production.svc.cluster.local:9200 | base64
  mpc-elasticsearch-url: c2VjcmV0
  mpc-elastic-apm-server-url: c2VjcmV0
  mpc-elastic-apm-secret-token: c2VjcmV0
  mpc-elasticsearch-host:
  mpc-elasticsearch-username:
  mpc-elasticsearch-password:
