apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpc-alert
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpc-alert
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25% 
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: mpc-alert
    spec:
      containers:
      - name: mpc-alert
        image: fadedreams7/mpc-alert:latest #local image
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: alert
          containerPort: 3001
        env:
          - name: ENABLE_APM
            value: '1'
          - name: NODE_ENV
            value: 'production'
          - name: CLIENT_URL
            value: 'https://mpcapp.live'
          - name: RABBITMQ_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-rabbitmq-endpoint
          - name: SENDER_EMAIL
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: sender-email
          - name: SENDER_EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: sender-email-password
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-elasticsearch-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key:  mpc-elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-elastic-apm-secret-token

---

apiVersion: v1
kind: Service
metadata:
  name: mpc-alert
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: mpc-alert
  ports:
  - name: alert
    port: 3001
    targetPort: 3001
    protocol: TCP
