# ClusterIP service
apiVersion: v1
kind: Service
metadata:
  name: mpc-kibana
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: mpc-kibana
  ports:
  - name: mpc-kibana
    port: 5601
    targetPort: 5601
    protocol: TCP

# NodePort service
apiVersion: v1
kind: Service
metadata:
  name: mpc-kibana-nodeport
  namespace: production
spec:
  type: NodePort
  selector:
    app: mpc-kibana
  ports:
  - name: mpc-kibana
    port: 5601
    targetPort: 5601
    nodePort: 31000  # Choose a nodePort value, for example, 31000
