
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpc-queue
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpc-queue
  template:
    metadata:
      labels:
        app: mpc-queue
    spec:
      containers:
      - name: mpc-queue
        image: rabbitmq:3.12.8-management-alpine
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: mpc
        - name: RABBITMQ_DEFAULT_PASS
          value: mpc
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            memory: 150Mi
            cpu: 100m
        ports:
        - name: queue
          containerPort: 5672
          protocol: TCP
        - name: mgmt
          containerPort: 15672
          protocol: TCP
        volumeMounts:
          - name: rabbittmq-local-storage
            mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbittmq-local-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc #from pv.yaml
