
apiVersion: v1
kind: Service
metadata:
  name: mpc-queue
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: mpc-queue #routes traffic into mpc-queue in the  queue.yaml pod
  ports:
  - name: queue
    port: 5672
    targetPort: queue #queue port from the queue.yaml
    protocol: TCP
  - name: mgmt
    port: 15672
    targetPort: mgmt #mgmt port from the queue.yaml
    protocol: TCP
