
apiVersion: v1
kind: Service
metadata:
  name: mpc-mongo
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: mpc-mongo
  ports:
  - name: mpc-mongo
    port: 27017
    targetPort: 27017
