
apiVersion: v1
kind: Service
metadata:
  name: mpc-mysql
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: mpc-mysql
  ports:
  - name: mpc-mysql
    port: 3306
    targetPort: 3306
