
apiVersion: v1
kind: Service
metadata:
  name: mpc-redis
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: mpc-redis # to route traffic to Pods with the label app=mpc-redis(every pod with label app=mpc-redis will be routed to this service)
  ports:
  - name: mpc-redis
    port: 6379 #(listen)the port that the Service will listen on inside the cluster.
    targetPort: 6379 #(forward)the port that the Service will route traffic to on the target Pods.
