apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpc-msg
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpc-msg
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: mpc-msg
    spec:
      containers:
      - name: mpc-msg
        image: fadedreams7/mpc-msg:latest #local image
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: msg
          containerPort: 3005
        env:
          - name: ENABLE_APM
            value: '1'
          - name: NODE_ENV
            value: 'production'
          - name: GATEWAY_JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: gateway-jwt-token
          - name: JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: jwt-token
          - name: RABBITMQ_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-rabbitmq-endpoint
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mongo-database-url
          - name: API_GATEWAY_URL
            value: 'http://mpc-gateway.production.svc.cluster.local:3000'
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-elasticsearch-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key:  mpc-elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-elastic-apm-secret-token         
---
apiVersion: v1
kind: Service
metadata:
  name: mpc-msg
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: mpc-msg
  ports:
  - name: msg
    port: 3005
    targetPort: 3005
    protocol: TCP

