
apiVersion: v1
kind: Service
metadata:
  name: mpc-kibana
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: mpc-kibana
  ports:
  - name: mpc-kibana
    port: 5601
    targetPort: 5601
    protocol: TCP
