
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpc-users
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpc-users
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25% 
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: mpc-users
    spec:
      containers:
      - name: mpc-users
        image: fadedreams7/mpc-users:latest #local image
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: users
          containerPort: 3003
        env:
          - name: ENABLE_APM
            value: '1'
          - name: NODE_ENV
            value: 'production'
          - name: GATEWAY_JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: gateway-jwt-token
          - name: JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: jwt-token
          - name: RABBITMQ_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-rabbitmq-endpoint
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mongo-database-url
          - name: API_GATEWAY_URL
            value: 'http://mpc-gateway.production.svc.cluster.local:3000'
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-redis-host
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-elasticsearch-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key:  mpc-elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: mpc-backend-secret
                key: mpc-elastic-apm-secret-token

---
apiVersion: v1
kind: Service
metadata:
  name: mpc-users
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: mpc-users
  ports:
  - name: users
    port: 3003
    targetPort: 3003
    protocol: TCP
