
apiVersion: v1
kind: Service
metadata:
  name: mpc-postgres
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: mpc-postgres
  ports:
  - name: mpc-postgres
    port: 5432
    targetPort: 5432
